[package]
name = "rnotify"
version = "0.1.0"
authors = ["Pavel Mukhanov <mukhanovpv@gmail.com>"]

[dependencies]
futures = "0.1.17"
tokio-core = "0.1.16"
tokio = "0.1.5"
hyper = "0.11.25"
hyper-tls = "0.1.3"
env_logger = "0.5.7"
serde_json = "1.0.13"
serde_derive = "1.0.37"
serde = "1.0.37"
